# How to run:

version: '2'
services:
  hubbledb:
    container_name: hubbledb
    image: 'mongo:latest'
    ports:
      - "27018:27017"
    volumes:
      - /vol/ages_paisagem/db:/var/lib/mysql:rw
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ages_hubble
      MONGO_INITDB_DATABASE: hubble
    networks:
      - hubble-network

  hubbleapi:
    container_name: hubbleapi
    build:
      context: .
      dockerfile: Dockerfile
    image: hubble-api:latest
    depends_on:
      - "hubbledb"
    expose:
      - "6725"
    ports:
      - "6725:4000"
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "-t", "0", "hubbledb:27018", "--", "npm","start", ]
    networks:
      - hubble-network

networks:
  hubble-network: