# How to run:

version: '2'
services:
  hubbledb:
    container_name: hubbledb
    image: 'mongo:latest'
    ports:
      - "27018:27017"
    volumes:
      - /vol/ages_hublle/db:/data/db
    networks:
      - hubble-network

  hubbleapi:
    container_name: hubbleapi
    build:
      context: .
      dockerfile: Dockerfile
    image: hubble-api:latest
    depends_on:
      - "hubbledb"
    expose:
      - "6725"
    ports:
      - "6725:4000"
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "-t", "0", "hubbledb:27018", "--", "npm","start", ]
    networks:
      - hubble-network

networks:
  hubble-network:
